name = "firstd1project"
main = "src/index.ts"
compatibility_date = "2023-04-25"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "firstd1"
database_id = "xxxxxxxxxxxxxxxxxx"

