version: '2'
services:
  master-a:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./master_a.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
  master-b:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./master_b.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
  slave:
    image: mysql:5.7
    ports:
      - '3308:3306'
    depends_on:
      - master-a
      - master-b
    volumes:
      - ./slave.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
